const SellerProduct = [
    {
        id: 1,
        img1: require("../../assets/product-11.jpg").default,
        img2: require("../../assets/product-11-02.jpg").default,
        img3: require("../../assets/product-11-02.jpg").default,
        title: "One Ummah",
        name: 'Waffle Cotton-Blend Hoodie',
        price: '$65.67',
        tooltip1: 'Grey',
        tooltip2: 'Green',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-03.jpg").default,
    },
    {
        id: 2,
        img1: require("../../assets/product-14.jpg").default,
        img2: require("../../assets/product-14-02.jpg").default,
        img3: require("../../assets/product-14-04.jpg").default,
        title: "Levi's",
        name: 'Packable Jacket',
        price: '$12.00',
        tooltip1: 'Black',
        tooltip2: 'Green',
        size1: 'S',
        size2: 'M',
        size3: 'XL',
        colorImg1: require("../../assets/texture-img-04.jpg").default,
        colorImg2: require("../../assets/texture-img-03.jpg").default,
        colorImg3: require("../../assets/texture-img-05.jpg").default,
    },
    {
        id: 3,
        img1: require("../../assets/product-15.jpg").default,
        img2: require("../../assets/product-15-02.jpg").default,
        img3: require("../../assets/product-15-03.jpg").default,
        title: "Gap",
        name: 'Douhglas Calfskin Buckle Belt',
        price: '$62.12',
        tooltip1: 'Choclate',
        tooltip2: 'Black',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-03.jpg").default,
    },
    {
        id: 4,
        img1: require("../../assets/product-10.jpg").default,
        img2: require("../../assets/product-10-02.jpg").default,
        img3: require("../../assets/product-10-04.jpg").default,
        title: "Levi's",
        name: 'Skinny Fit Stretch Mesh Polo',
        price: '$322.00',
        tooltip1: 'LightBlue',
        tooltip2: 'LightPink',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-04.jpg").default,
    },
    {
        id: 5,
        img1: require("../../assets/product-13.jpg").default,
        img2: require("../../assets/product-13-02.jpg").default,
        img3: require("../../assets/product-13-03.jpg").default,
        title: "Lacoste",
        name: 'Saffiano Leather Belt',
        price: '$96.81',
        tooltip1: 'White',
        tooltip2: 'Brown',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-03.jpg").default,
        colorImg2: require("../../assets/texture-img-04.jpg").default,
        colorImg3: require("../../assets/texture-img-05.jpg").default,
    },
    {
        id: 6,
        img1: require("../../assets/product-06.jpg").default,
        img2: require("../../assets/product-06-02.webp").default,
        img3: require("../../assets/product-06-04.jpg").default,
        title: "Levi's",
        name: 'Skinny Fit Stretch Mesh Polo',
        price: '$322.00',
        tooltip1: 'Light-Blue',
        tooltip2: 'Beige',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-04.jpg").default,
        colorImg3: require("../../assets/texture-img-03.jpg").default,
    },
    {
        id: 7,
        img1: require("../../assets/product-15.jpg").default,
        img2: require("../../assets/product-15-02.jpg").default,
        img3: require("../../assets/product-15-03.jpg").default,
        title: "Zara",
        name: 'Wimbledon Cross Court Cap',
        price: '$140.00',
        tooltip1: 'Black',
        tooltip2: 'White',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-02.jpg").default,
        colorImg2: require("../../assets/texture-img-05.jpg").default,
        colorImg3: require("../../assets/texture-img-01.jpg").default,
    },
    {
        id: 8,
        img1: require("../../assets/product-16.jpg").default,
        img2: require("../../assets/product-16-02.jpg").default,
        img3: require("../../assets/product-16-02.jpg").default,
        title: "Gap",
        name: 'Custom Fit Soft-Touch Polo',
        price: '$5.00',
        tooltip1: 'Black',
        tooltip2: 'White',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-04.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-01.jpg").default,
    }

];


export default SellerProduct