const products = [
    {
        id: 1,
        img1: require("../../assets/product-01.jpg").default,
        img2: require("../../assets/product-01-02.jpg").default,
        img3: require("../../assets/product-01-03.jpg").default,
        title: "Gussa",
        name: 'Relaxed-Fit Cotton Shirt',
        price: '$12.00',
        tooltip1: 'Grey',
        tooltip2: 'Green',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-03.jpg").default,
    },
    {
        id: 2,
        img1: require("../../assets/product-02.jpg").default,
        img2: require("../../assets/product-02-02.jpg").default,
        img3: require("../../assets/product-02-04.jpg").default,
        title: "One Ummha",
        name: 'East Hampton Fleece Hoodie',
        price: '$65.60',
        tooltip1: 'Black',
        tooltip2: 'Gray',
        size1: 'S',
        size2: 'M',
        size3: 'XL',
        colorImg1: require("../../assets/texture-img-04.jpg").default,
        colorImg2: require("../../assets/texture-img-03.jpg").default,
        colorImg3: require("../../assets/texture-img-05.jpg").default,
    },
    {
        id: 3,
        img1: require("../../assets/product-05.jpg").default,
        img2: require("../../assets/product-05-02.jpg").default,
        img3: require("../../assets/product-05-03.jpg").default,
        title: "Gussa",
        name: 'Relaxed-Fit Cotton Shirt',
        price: '$12.00',
        tooltip1: 'Grey',
        tooltip2: 'Green',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-03.jpg").default,
    },
    {
        id: 4,
        img1: require("../../assets/product-06.jpg").default,
        img2: require("../../assets/product-06-02.webp").default,
        img3: require("../../assets/product-06-04.jpg").default,
        title: "OXford",
        name: 'Plaid Cotton Oxford Shirt',
        price: '$55.91',
        tooltip1: 'Blue',
        tooltip2: 'Pink',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-04.jpg").default,
    },
    {
        id: 5,
        img1: require("../../assets/product-09.jpg").default,
        img2: require("../../assets/product-09-02.jpg").default,
        img3: require("../../assets/product-09-02.jpg").default,
        title: "Gussa",
        name: 'Two-Tone Sleeveless Dress',
        price: '$177.91',
        tooltip1: 'Black',
        tooltip2: 'White',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-03.jpg").default,
        colorImg2: require("../../assets/texture-img-04.jpg").default,
        colorImg3: require("../../assets/texture-img-05.jpg").default,
    },
    {
        id: 6,
        img1: require("../../assets/product-10.jpg").default,
        img2: require("../../assets/product-10-02.jpg").default,
        img3: require("../../assets/product-10-04.jpg").default,
        title: "Levi's",
        name: 'Skinny Fit Stretch Mesh Polo',
        price: '$322.00',
        tooltip1: 'Light-Blue',
        tooltip2: 'Beige',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-01.jpg").default,
        colorImg2: require("../../assets/texture-img-04.jpg").default,
        colorImg3: require("../../assets/texture-img-03.jpg").default,
    },
    {
        id: 7,
        img1: require("../../assets/product-14.jpg").default,
        img2: require("../../assets/product-14-02.jpg").default,
        img3: require("../../assets/product-14-04.jpg").default,
        title: "Levi's",
        name: 'Packable Jacket',
        price: '$12.00',
        tooltip1: 'Black',
        tooltip2: 'Green',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-02.jpg").default,
        colorImg2: require("../../assets/texture-img-05.jpg").default,
        colorImg3: require("../../assets/texture-img-01.jpg").default,
    },
    {
        id: 8,
        img1: require("../../assets/product-16.jpg").default,
        img2: require("../../assets/product-16-02.jpg").default,
        img3: require("../../assets/product-16-02.jpg").default,
        title: "Gap",
        name: 'Custom Fit Soft-Touch Polo',
        price: '$5.00',
        tooltip1: 'Black',
        tooltip2: 'White',
        size1: 'S',
        size2: 'M',
        size3: 'X',
        colorImg1: require("../../assets/texture-img-04.jpg").default,
        colorImg2: require("../../assets/texture-img-02.jpg").default,
        colorImg3: require("../../assets/texture-img-01.jpg").default,
    }
];

export default products